name: Publish to Azure Artifacts

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  PublishToAzureArtifacts:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      # Publish each subproject independently.  Using publish task causes all subprojects to
      # be published to all repositories which results in duplicate publication errors.

      - name: Publish dao-api to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishDaoApiPubPublicationToDaoApiAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish domain to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishDomainPubPublicationToDomainAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish handlers to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishHandlersPubPublicationToHandlersAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish handlers-api to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishHandlersApiPubPublicationToHandlersApiAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish interceptors to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishInterceptorsPubPublicationToInterceptorsAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish producers-api to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishProducersApiPubPublicationToProducersApiAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish services-api to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishServicesApiPubPublicationToServicesApiAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish transformers to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishTransformersPubPublicationToTransformersAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish utils to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishUtilsPubPublicationToUtilsAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish validators to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishValidatorsPubPublicationToValidatorsAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish sdt-common to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishSdtCommonPubPublicationToSdtCommonAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash
