name: Publish to Azure Artifacts

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  PublishToAzureArtifacts:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Publish dao-api to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishAzureArtDaoApiPublicationToDaoApiAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish domain to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishAzureArtDomainPublicationToDomainAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish handlers to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishAzureArtHandlersPublicationToHandlersAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish handlers-api to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishAzureArtHandlersApiPublicationToHandlersApiAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish interceptors to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishAzureArtInterceptorsPublicationToInterceptorsAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish producers-api to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishAzureArtProducersApiPublicationToProducersApiAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish services-api to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishAzureArtServicesApiPublicationToServicesApiAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish transformers to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishAzureArtTransformersPublicationToTransformersAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish utils to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishAzureArtUtilsPublicationToUtilsAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish validators to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishAzureArtValidatorsPublicationToValidatorsAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash

      - name: Publish sdt-common to Azure DevOps Artifacts
        run: |
          ./gradlew --info publishAzureArtSdtCommonPublicationToSdtCommonAzureArtifactsRepository
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        shell: bash
